import { atom } from "jotai";

export const currentFilterCategory = atom("top-up");

export const setCurrentFilterCategory = atom(null, (get, set, category) => {
  set(currentFilterCategory, category);
});

export const gameCategories = atom([
  {
    id: 1,
    url: "/mobile-legends",
    title: "Mobile Legends",
    image: "/images/lagipopuler/mobile-legends.webp",
    category: "top-up",
  },
  {
    id: 2,
    url: "/free-fire",
    title: "Free Fire",
    image: "/images/lagipopuler/ff.webp",
    category: "top-up",
  },
  {
    id: 3,
    url: "/pubg-mobile",
    title: "PUBG Mobile",
    image: "/images/lagipopuler/pubgm.webp",
    category: "top-up",
  },
  {
    id: 4,
    url: "/garena-undawn",
    title: "Garena Undawn",
    image: "/images/lagipopuler/Garena-Undawn.png",
    category: "top-up",
  },
  {
    id: 5,
    url: "/garena-undawn",
    title: "Garena Undawn",
    image: "/images/lagipopuler/Gold-Garena-Undawn.png",
    category: "top-up",
  },
  {
    id: 6,
    url: "/metal-slug",
    title: "Metal Slug",
    image: "/images/lagipopuler/metal-slug.png",
    category: "top-up",
  },
  {
    id: 7,
    url: "/valorant",
    title: "Valorant",
    image: "/images/lagipopuler/valorant.png",
    category: "top-up",
  },
  {
    id: 8,
    url: "/genshin-impact",
    title: "Genshin Impact",
    image: "/images/lagipopuler/gensin-impact.png",
    category: "top-up",
  },
  {
    id: 9,
    url: "/genshin-impact",
    title: "Genshin Impact",
    image: "/images/lagipopuler/gensin-impact.png",
    category: "top-up",
  },
  {
    id: 10,
    url: "/star-rail-1",
    title: "Star Rail 1",
    image: "/images/lagipopuler/Honkai-Star-Rail.png",
    category: "top-up",
  },
  {
    id: 11,
    url: "/star-rail-2",
    title: "Star Rail 2",
    image: "/images/lagipopuler/Honkai-Star-Rail.png",
    category: "top-up",
  },
  {
    id: 12,
    url: "/honkai-impact",
    title: "Honkai Impact",
    image: "/images/lagipopuler/Honkai-Impact-3.png",
    category: "top-up",
  },
  {
    id: 13,
    url: "/tower-of-fantasy",
    title: "Tower of Fantasy",
    image: "/images/lagipopuler/Tower-of-Fantasy.png",
    category: "top-up",
  },
  {
    id: 14,
    url: "/ea-sports-fc",
    title: "EA SPORTS FC",
    image: "/images/lagipopuler/EA-SPORTS-FC.png",
    category: "top-up",
  },
  {
    id: 15,
    url: "/call-of-duty",
    title: "Call of Duty",
    image: "/images/lagipopuler/Call-of-Duty.png",
    category: "top-up",
  },
  {
    id: 16,
    url: "/point-blank",
    title: "Point Blank",
    image: "/images/lagipopuler/point-blank.png",
    category: "top-up",
  },
  {
    id: 17,
    url: "/hago",
    title: "Hago",
    image: "/images/lagipopuler/hago.png",
    category: "top-up",
  },
  {
    id: 18,
    url: "/arena-of-valor",
    title: "Arena of Valor",
    image: "/images/lagipopuler/arena-of-valor.png",
    category: "top-up",
  },
  {
    id: 19,
    url: "/clash-of-clans",
    title: "Clash of Clans",
    image: "/images/lagipopuler/clash-of-clans.png",
    category: "top-up",
  },
  {
    id: 20,
    url: "/clash-royale",
    title: "Clash Royale",
    image: "/images/lagipopuler/clash-royale.png",
    category: "top-up",
  },
  {
    id: 21,
    url: "/hay-day",
    title: "Hay Day",
    image: "/images/lagipopuler/hay-day.png",
    category: "top-up",
  },
  {
    id: 22,
    url: "/brawl-stars",
    title: "Brawl Stars",
    image: "/images/lagipopuler/brawl-stars.png",
    category: "top-up",
  },
  {
    id: 23,
    url: "/eggy-party",
    title: "Eggy Party",
    image: "/images/lagipopuler/eggy-party.png",
    category: "top-up",
  },
  {
    id: 1,
    url: "/telkomsel",
    title: "Telkomsel",
    image: "/images/pulsa/telkomsel.png",
    category: "pulsa",
  },
  {
    id: 2,
    url: "/by-u",
    title: "by.U",
    image: "/images/pulsa/by.u.png",
    category: "pulsa",
  },
  {
    id: 3,
    url: "/axis",
    title: "Axis",
    image: "/images/pulsa/axis.png",
    category: "pulsa",
  },
  {
    id: 4,
    url: "/xl-axiata",
    title: "XL Axiata",
    image: "/images/pulsa/xl-axiata.png",
    category: "pulsa",
  },
  {
    id: 5,
    url: "/indosat",
    title: "Indosat",
    image: "/images/pulsa/indosat.png",
    category: "pulsa",
  },
  {
    id: 6,
    url: "/tri",
    title: "Tri",
    image: "/images/pulsa/tri.png",
    category: "pulsa",
  },
  {
    id: 7,
    url: "/smartfren",
    title: "Smartfren",
    image: "/images/pulsa/smartfren.png",
    category: "pulsa",
  },
  {
    id: 8,
    url: "/token-pln",
    title: "Token PLN",
    image: "/images/pulsa/token-pln.png",
    category: "pulsa",
  },
  {
    id: 1,
    url: "/garena-shell",
    title: "Garena Shell",
    image: "/images/voucher/garena-shell.png",
    category: "voucher",
  },
  {
    id: 2,
    url: "/point-blank",
    title: "Point Blank",
    image: "/images/voucher/point-blank.png",
    category: "voucher",
  },
  {
    id: 3,
    url: "/google-play",
    title: "Google Play",
    image: "/images/voucher/google-play.png",
    category: "voucher",
  },
  {
    id: 4,
    url: "/stumble-guys",
    title: "Stumble Guys",
    image: "/images/voucher/stumble-guys.png",
    category: "voucher",
  },
  {
    id: 5,
    url: "/play-station",
    title: "Play Station",
    image: "/images/voucher/play-station.png",
    category: "voucher",
  },
  {
    id: 1,
    url: "/mangatoon",
    title: "MangaToon",
    image: "/images/Entertainment/mangatoon.png",
    category: "entertainment",
  },
  {
    id: 2,
    url: "/lita",
    title: "Lita",
    image: "/images/Entertainment/lita.png",
    category: "entertainment",
  },
  {
    id: 3,
    url: "/mango-live",
    title: "Mango Live",
    image: "/images/Entertainment/mango-live.png",
    category: "entertainment",
  },
  {
    id: 4,
    url: "/sugar-live",
    title: "Sugar Live",
    image: "/images/Entertainment/sugar-live.png",
    category: "entertainment",
  },
  {
    id: 5,
    url: "/viu",
    title: "Viu",
    image: "/images/Entertainment/viu.png",
    category: "entertainment",
  },
  {
    id: 6,
    url: "/netflix",
    title: "Netflix",
    image: "/images/Entertainment/netflix.png",
    category: "entertainment",
  },
  {
    id: 7,
    url: "/bilibili",
    title: "BiliBili",
    image: "/images/Entertainment/bilibili.png",
    category: "entertainment",
  },
  {
    id: 8,
    url: "/wetv-vip",
    title: "WeTV VIP",
    image: "/images/Entertainment/wetv-vip.png",
    category: "entertainment",
  },
  {
    id: 9,
    url: "/vidio",
    title: "Vidio",
    image: "/images/Entertainment/vidio.png",
    category: "entertainment",
  },
  {
    id: 10,
    url: "/bigo-live",
    title: "Bigo Live",
    image: "/images/Entertainment/bigo-live.png",
    category: "entertainment",
  },
  {
    id: 1,
    url: "/join-reseller",
    title: "JOIN RESELLER",
    image: "/images/join-reseller/join-reseller.png",
    category: "join-reseller",
  },
]);
